const assert=require('node:assert/strict');
const E=require('./engine.js');
const base={store:'monetka',adults:2,children:1,meals:{breakfast:true,lunch:true,dinner:true},batchCooking:true,budget:9000,exclusions:[],equipment:{oven:true,multicooker:true,blender:true,meatGrinder:true,vacuum:true},maxTime:90,vegDays:1};
assert.deepEqual(E.validateData(),[],'data validation');
const p1=E.buildPlan(base),p2=E.buildPlan(base);
assert.equal(JSON.stringify(p1),JSON.stringify(p2),'deterministic plan');
assert.equal(p1.entries.length,21,'three meals x seven days');
assert.ok(p1.shopping.length>15,'shopping list populated');
assert.equal(new Set(p1.shopping.map(x=>x.id)).size,p1.shopping.length,'no duplicate products');
assert.ok(p1.cost>0 && Number.isFinite(p1.cost),'valid cost');
for(const x of p1.entries) assert.ok(x.stats.cost>0 && x.stats.kcal>0,`valid stats ${x.dish.id}`);
const noPork=E.buildPlan({...base,exclusions:['свинина']});
for(const x of noPork.entries) assert.ok(!E.dishTags(x.dish).has('свинина'),`pork excluded: ${x.dish.id}`);
const noGluten=E.buildPlan({...base,exclusions:['глютен']});
for(const x of noGluten.entries) assert.ok(!E.dishTags(x.dish).has('глютен'),`gluten excluded: ${x.dish.id}`);
const noGear=E.buildPlan({...base,equipment:{oven:false,multicooker:false,blender:false,meatGrinder:false,vacuum:false}});
for(const x of noGear.entries) assert.ok((x.dish.equipment||[]).every(k=>k==='stove'||k==='vacuum'),`equipment filtered: ${x.dish.id}`);
const dinners=E.buildPlan({...base,meals:{breakfast:false,lunch:false,dinner:true}});
assert.equal(dinners.entries.length,7,'dinner-only plan');
const low=E.buildPlan({...base,budget:2500});
assert.ok(Number.isFinite(low.cost) && low.entries.length===21,'low budget does not crash');
console.log(JSON.stringify({tests:'passed',dishes:E.DISHES.length,products:Object.keys(E.PRODUCTS).length,cost:p1.cost,lowBudgetCost:low.cost}));
